// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQTuArr9zGYHYEcv-8hfS5024RMDsxHV0',
    appId: '1:125561115721:web:b03a4d99c56a3db34c9b98',
    messagingSenderId: '125561115721',
    projectId: 'bookworm-e489c',
    authDomain: 'bookworm-e489c.firebaseapp.com',
    storageBucket: 'bookworm-e489c.firebasestorage.app',
    measurementId: 'G-8YPNZZLZ9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN4PTdxowsfNCv9tCPmRNl3Ft7nPqwnw4',
    appId: '1:125561115721:android:e7bf9ee97fd3a9354c9b98',
    messagingSenderId: '125561115721',
    projectId: 'bookworm-e489c',
    storageBucket: 'bookworm-e489c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCINJUU5cP6dxWhSbEUtwvKBKk4xMkrTjA',
    appId: '1:125561115721:ios:a16c9efb414255d54c9b98',
    messagingSenderId: '125561115721',
    projectId: 'bookworm-e489c',
    storageBucket: 'bookworm-e489c.firebasestorage.app',
    iosBundleId: 'com.example.bookworm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCINJUU5cP6dxWhSbEUtwvKBKk4xMkrTjA',
    appId: '1:125561115721:ios:a16c9efb414255d54c9b98',
    messagingSenderId: '125561115721',
    projectId: 'bookworm-e489c',
    storageBucket: 'bookworm-e489c.firebasestorage.app',
    iosBundleId: 'com.example.bookworm',
  );
}
